### ISSUE TITLE
Enable zooming of images on mobile devices

### ISSUE THREAD

**Issue by ahmednooor** [feimosi/baguetteBox.js#66] opened 2016-03-12 08:09 UTC
when the image is opened in the popup screen, zooming is disabled or almost unusable. since the mobile width is short so if u could add zooming enhancement, it would be a great experience for user to zoom in the opened image.
thanks

**Comment by feimosi** [comment] 2016-03-13 15:42
I guess you're talking abour [`<meta name="viewport">` property](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag). You can use it to enable zooming within a website on mobile devices. Of course I could implement some custom zooming functionality, but that's a complex and cumbersome task.

**Comment by ahmednooor** [comment] 2016-03-14 09:12
i am very new to html btw. i added the viewport and didnt restrict it to zoom this is my viewport tag.

<meta name="viewport" content="width=device-width, initial-scale=1.0">

when i zoom in by two fingers it doesnt  zoom. and instead the picture slides to another  one. the double tap zoom doesnt work either.

btw thanks for the plugin or whatever its called in technical form :)

**Comment by feimosi** [comment] 2016-03-15 18:38
Well, I haven't thought about that. Could you try removing the 'touch' logic from the script (touch event listeners) and see whether the zooming works? Then I could implement an easy solution.

**Comment by ahmednooor** [comment] 2016-03-17 11:47
well i am new to programming and dont know a thing about js. I will try it and get back to you.

**Comment by ahmednooor** [comment] 2016-03-17 15:02
Ok I did this,
at line 58 changed the value of touchFlag from false to true.
at line 114 changed the value of touchFlag from false to true.
This disabled the slide to navigate next and previous images in the gallery but enabled zooming.

For the navigation i did this.
at line 38 changed the value of buttons from 'auto' to true.

Hope this helps.

**Comment by feimosi** [comment] 2016-03-19 12:05
Thanks, that's exactly what I wanted to confirm. Now I think it should be quite easy to resolve this issue.

**Comment by ahmednooor** [comment] 2016-03-20 09:23
glad it helped :) looking forward to the enhancement.

**Comment by filmor** [comment] 2016-05-31 16:13
Any hint on what actually goes wrong here?

**Comment by ahmednooor** [comment] 2016-06-01 12:46
i think the code is yet restricted to have only one touch event and does not recognize more than one and forces them to act like a single touch event instead of ignoring them and prevents default browser zoom on multi touch zoom. (i am a newbie so could be wrong) thanks.

**Comment by feimosi** [comment] 2016-06-02 14:22
@filmor It's because the script doesn't support multitouch.
We have a touch listener and we take the first move as a swipe in either direction instead of zooming in (handled by the browser). The solution is to ignore the event when more than one `touchstart` events fire. I just don't have time for that now. PRs and older issues take precedence.

**Comment by feimosi** [comment] 2016-06-14 20:43
@ahmednooor @filmor I've managed to fix that issue, could you test it yourselves before I merge it? It's on a separate branch:
https://github.com/feimosi/baguetteBox.js/tree/bugfix/66-handle-multitouch

**Comment by ahmednooor** [comment] 2016-06-22 17:55
sorry for not replying in time as i use github less. will sure test it. just tell me if u have merged it with master branch because the link u provided is not valid anymore. thanks :)

**Comment by feimosi** [comment] 2016-06-22 18:22
@ahmednooor no problem, I've merged it with https://github.com/feimosi/baguetteBox.js/tree/dev yesterday. You've got like a week to test it before I make a release :)

**Comment by ahmednooor** [comment] 2016-06-22 18:45
Tested Branch: Dev
Folder: src
File: baguetteBox.js

Tested Devices: 
1. Lumia 630 Windows phone 8.1 Internet Explorer.
2. Huawei y5 Android 4.4.2 Chrome and Firefox.

Issues:
Lumia 630 windows phone 8.1 IE:
Zooming works and different parts of the zoomed image can be viewed by moving the image with single finger swipe. But when the image has been zoomed and then zoomed out i.e multi touch ignore script has been executed then u cant swipt to the next image unless close the box first via cross icon and then opening it again by taping the image then swipe to next image works but if u zoom it stops again unless u close the box and then reopen it.

Huawei y5 Android 4.4.2 Chrome: 
Zooming works but u cant see the other portions of a zoomed image via single finger swipe. It swipes to next image instead of just moving the zoomed image. While after zooming out the swipe to next image works and u dont need to close the box and reopen it as in IE on windows phone 8.1.

Huawei y5 Android 4.4.2 Firefox: 
Zooming does not work on image only the icon is zoomed and the webpage behind the box overlay but the image remains fixed to width or height and does not zoom in.

Possible Reasons behind the issue:
1. Perhaps the difference in method of different browser engines to execute Javascript .
2. On Chrome when the script to ignore multi touch is executed it does not disable the swipe to next image script and thts y the image zooms but when u move it to see other areas of zoomed image the swipe to next image script runs and the zoomed image instead of moving, jumps to the next image.
3. On IE when the script to ignore multi touch is run the browser disables the script for swiping to next image permanently unless u close the box and reopens it i.e restarting the plugin.
4. On Firefox, no idea perhaps its too stubborn to adapt any change.

Personal Remarks:
Thanks a lot for looking into this matter. I wont insist you anymore to work on this matter unless you yourself want to, as the solution in itself has become complicated.
Thanks a lot and sorry for my bad English :)

**Comment by ahmednooor** [comment] 2016-06-22 18:49
btw this is the web project on which i have used the plugin. u can check it there too.
http://ahmednooor.github.io/its/

**Comment by feimosi** [comment] 2016-06-22 19:23
Thank you too for such a thorough investigation. Here are my thoughts:

* IE: It all sounds like the multi touch is detected in a wrong way. That may be caused by the browser. Basically, what my solution does, is to count new touch events and decrement on touch end event - you can see it in the commit, nothing really complex. Unfortunately I don't have any access to a Windows Phone, if you are able to debug it yourself, fell free to drop me a message. The basic scenario is to add a `console.log()` in `touchstartHandler()` and see how `touch.count` is incremented.

* Chrome: I was aware of this problem, but I can't find a way to easily detect if a webpage is zoomed in, so I assumed users can use two fingers to move around the image (worked fine on my phone). What do you think?

* Firefox: I haven't tested it, will do that soon.

**Comment by ahmednooor** [comment] 2016-06-22 19:46
yes you are right on chrome moving the image with double finger swipe does move the image instead of jumping to the next. 
well actually m just a beginner and i may understand a little bit logic behind programming language but i certainly dont know how it works in terms of its syntax m just at the starting line in Javascript and jquery and touch events i think is far too much advanced for me. though i would surely like to give it a try and play with it but dont count on me :).
Btw the days of IE are almost over now i would try to get my hands on Edge on windows phone 10 if i could and see if it works fine on it.
Thanks and regards :)

**Comment by feimosi** [comment] 2016-06-23 09:40
Ok, sure, then let's not focus on IE with this. I'm just gonna see how to repair it on Firefox. Regards :)

**Comment by ahmednooor** [comment] 2016-06-24 16:14
Tested Device: Lumia 435 window phone 10 Edge
It worked exactly like on google chrome the image zoomed and to move zoomed image double finger gesture is needed while singer finger  swipes to next image in zoomed mode. After zooming out swipe to next or previous image works fine unlike on IE and exactly like chrome. The firefox is the remaining problem i think. Do check it on safari on ios as apple devices are not in my reach.

Btw if you could somehow make it possible to move zoomed image via single finger instead of double tht will be great because that is the default reaction of a user. I myself didnt know that it can be moved by double finger until u told and i kept using single finger while the image swiped to next instead of moving.

I tried to experiment a little as my advanced knowledge is almost null. I couldnt succeed while i have some suggestions. They may be impossible in terms of syntax limits but there are two logics to disable single finger swipe to next previous image in zoomed mode.

1. Try to store single touch and multitouch in their separate variables instead of one. and disable the function which jumps to next or previous image via single finger when multitouch variable or function has been fired hence when multitouch has bee fired the single touch swipe to next previous function of plugin is ignored and browser's single touch to move a zoomed webpage is enabled.

2. When a multitouch is detected add some script to detect the zoom level if a page has been zoomed then disable those single swipe to next or previous function and when the zoom level is at default then enable the single swipe to next or previous function is enabled.

I know its easier said then done so its totally up to you if u like to or leave it with double finger swipe for moving a zoomed image. The zooming functionality is working so the goal to much extent has been achieved. Thanks for looking into it :) and best of luck :)

**Comment by feimosi** [comment] 2016-06-29 18:19
Thanks for your suggestions. I'm totally aware that the current solution is only partially valid and not the most convenient one. I really would like to fix it but (answering your proposals):

1. It's impossible to properly detect zoomed-in web page that way. There are too many possibilities, when the user zoomed in and out, by how much, did he only touch the screen with two fingers?

2. That's the way I've found on the Internet during my quick research. The main drawback is that browsers vary here a lot. There is no unified way to detect zoom level, or at least I haven't found one. I'll try searching more again, though.

Firefox is still to be checked. Unfortunately I also don't have any access to iOS / Safari.
I'll keep you informed :)

**Comment by ahmednooor** [comment] 2016-06-30 18:35
first of all thanks for replying to my suggestions :) and sorry for keep giving suggestions again and again. 

there is a plugin called lighcase which have the ability to slide to navigate and pinch to zoom, u can review their code if u want to, but it is in jquery. here is the link to it.
https://github.com/cbopp-art/lightcase

ultimately i think the last option will be to add a zoom icon besides the cross icon which would zoom if clicked upon independently of touch gestures. a plugin called lightgallery does that so u can check that too. it is too in jquery. here is the link to it.
https://github.com/sachinchoolur/lightGallery

i wont be giving suggestions any further. if u have any update i would be delighted to know.
you have done a great job. what i like about this plugin is that its in vanilla JS its light weight its fast and simple. so best of luck and peace :)

**Comment by feimosi** [comment] 2016-07-23 09:21
Hi again and sorry, I totally forgot to reply :)

I've tried lightcase.js, but _pinch to zoom_ doesn't work for me at all (latest Chrome on Android). I don't see any touch-related code in the source either.

Zoom icon from lightGallery is also an option, I'll consider it probably in the 2.0 release.

I'll be looking into this problem and keep you informed. It's just I don't have much time now :)

**Comment by ahmednooor** [comment] 2016-07-24 12:07
Hi, and no problem at all :) the reason u r not able to pnch zoom is because at their demo page they have restricted zooming in their meta viewport tag.
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

I have used the plugin on one of my projects and i can zoom it by pinching. here is the link,
http://ahmednooor.github.io/abeelss/portfolio.html

thanks and I understand no need to hurry, take your time :)

**Comment by feimosi** [comment] 2016-07-25 20:16
Oh, right, `user-scalable=no` explains everything :)
Hopefully someday will fight this issue 👍

**Comment by ahmednooor** [comment] 2016-07-26 16:15
yeah sure :)

**Comment by ahmednooor** [comment] 2016-08-31 12:13
hey @feimosi  hope u r fine and sorry to disturb u again. i did some tweaking on one of the lil bit previous version or maybe the one from the master branch. it seems to be working on chrome on android but not on firefox. this is what i did. please test it to see if its working or not. thanks a lot :)

var viewport = window.innerWidth;
    var touchstartHandler = function(event) {
        // Save x and y axis position
        if (window.innerWidth == viewport) {
        touchStartX = event.changedTouches[0].pageX;
        touchStartY = event.changedTouches[0].pageY;
            return true;
        } else if (window.innerWidth > viewport) {
            return false;
        }
    };
    var touchmoveHandler = function(event) {
        // If action was already triggered return
        var touches = event.length;
        if (window.innerWidth == viewport && touches != 2) {
            if (touchFlag) {
                return;
            }
//            event.preventDefault ? event.preventDefault() : event.returnValue = false; // jshint ignore:line
            var touch = event.touches[0] || event.changedTouches[0];
            // Move at least 40 pixels to trigger the action
            if (touch.pageX - touchStartX > 40) {
                touchFlag = true;
                showPreviousImage();
            } else if (touch.pageX - touchStartX < -40) {
                touchFlag = true;
                showNextImage();
            // Move 100 pixels up to close the overlay
            } else if (touchStartY - touch.pageY > 100) {
                hideOverlay();
            }
        } else if (window.innerWidth > viewport) {
            return false;
        }
    };
    var touchendHandler = function() {
        if (window.innerWidth == viewport) {
            touchFlag = false;
        } else if (window.innerWidth > viewport) {
            touchFlag = true;
        }
    };

**Comment by ahmednooor** [comment] 2016-09-03 07:34
sorry, there is a correction.
var touches = event.touches.length; not, var touches = event.length;

btw i have created a small lightbox script with javascript and used this kind of technique in it. it would be extremely helpful for me if you give your opinion, no insistence though :). Thanks in advance Plus i have learnt very much about touch events from your touch event code, so thanks a lot for that :)

This is the link to script,
https://github.com/ahmednooor/halkaBox.js

And this is how i used the above mentioned technique,
```javascript
touchEnabled = false;
viewport = window.innerWidth;
function touchStart(event) {
    // to confirm it is a single touch and browser is not zoomed in
    if (window.innerWidth === viewport && event.touches.length === 1) {
        // for collecting x axis position
        touchPositionX = event.changedTouches[0].pageX;
        return;
    } else {
        return false;
    }
}
function touchMove(event) {
    var touch = event.touches[0] || event.changedTouches[0],
        touches = event.touches.length;
    // to check if touchEnabled is false, touches are not two and browser is not zoomed in
    if (touchEnabled === false && window.innerWidth === viewport && touches !== 2) {
        event.preventDefault();
        // slide at least below mentioned pixels to trigger next or previous
        if (touch.pageX - touchPositionX > 50) {
            touchEnabled = true;
            previous();
        } else if (touch.pageX - touchPositionX < -50) {
            touchEnabled = true;
            next();
        }
        return;
    } else {
        return false;
    }
}
function touchEnd() {
    touchEnabled = false;
}
```

Thanks and Peace.

**Comment by feimosi** [comment] 2016-09-05 20:34
@ahmednooor thanks a lot for your engagement in this issue, I appreciate that. Unfortunately currently I'm very busy so I can't promise when I'm gonna check this code out. Also I'd gladly look at you lightbox too, just don't know when.

I'm gonna reopen this issue so I won't forget about it :)

**Comment by ahmednooor** [comment] 2016-09-05 22:23
no problem at all, take your time and best of luck :)

**Comment by feimosi** [comment] 2017-09-26 10:02
Hello @ahmednooor, sorry for such a long time without updates.
I've tried your latest solution, but `window.innerWidth === viewport` doesn't detect zoom in Chrome on Android, I've tested several other solutions with no luck. The rest of the script seems to be working fine on mobile, so I'm gonna close this issue. If you find any new problems feel free to contact me.

Also I took a look at halkaBox.js, it looks very neat, congratulations! :)

**Closed by feimosi** 2017-09-26 10:02 UTC
Labels: bug

**Comment by ahmednooor** [comment] 2017-10-17 10:52
@feimosi  
hey, hope u r fine. i have tried to add the zoom. please review. thanks.

demo:
https://ahmednooor.github.io/baguetteBoxZoom/

files:
https://github.com/ahmednooor/baguetteBoxZoom/blob/gh-pages/baguetteBox.js
https://github.com/ahmednooor/baguetteBoxZoom/blob/gh-pages/baguetteBox.css

tested on chrome and firefox on android.

regards.

**Comment by naveenparth** [comment] 2018-05-01 11:45
@ahmednooor your solutions works fine but in it, images overlaps (z-index) the Image captions 'figcaption'.

**Comment by techteamdev1** [comment] 2022-04-15 15:29
const opts = {
            onChange: function(currentIndex, imagesCount) {
                //zoom function 
                // let currentSliderID="#baguette-img-"+currentIndex;
                $("#baguette-img-"+currentIndex).siblings().removeAttr("style");
                const zoomElement = document.getElementById("baguette-img-"+currentIndex);
                let zoom = 1;
                const ZOOM_SPEED = 0.1;
                document.addEventListener("wheel", function(e) {  
                    if(e.deltaY > 0){    
                        $("#baguette-img-"+currentIndex).siblings().removeAttr("style");
                            zoomElement.style.transform = `scale(${zoom += ZOOM_SPEED})`;                       
                    }
                    else{    
                        $("#baguette-img-"+currentIndex).siblings().removeAttr("style");
                        if(zoom>0.5){
                            zoomElement.style.transform = `scale(${zoom-=ZOOM_SPEED})`;
                        }else{
                            zoomElement.style.transform = `scale(${zoom=ZOOM_SPEED})`;
                        }
                    }
                });
                //  console.log("ON CHANGE", currentIndex);console.log("ON imagesCount", imagesCount); 
                }
        }
        baguetteBox.run(`#${this.$mainCarousel.attr('id')}`,opts);
