### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by thr-33** [feimosi/baguetteBox.js#64] opened 2016-02-26 09:45 UTC
Any chance for video support? I know it wouldn't be easy but even the ability to use the default html video player in the lightbox would rock

**Comment by feimosi** [comment] 2016-03-07 11:26
Hi, sorry, but currently it's not possible. BaguetteBox was prepared only with images in mind. So the whole codebase is based upon this assumption. 

Duplicate of #21

**Closed by feimosi** 2016-03-07 11:26 UTC
