### ISSUE TITLE
Problems with babel: baguetteBox is undefined

### ISSUE THREAD

**Issue by godmok** [feimosi/baguetteBox.js#135] opened 2016-12-13 21:13 UTC
Hi, I used baguettBox.js and had some problems in my configuration with gulp and babel. I don't know if it is more a pull request or an issue, so:

The problem here comes with the definition of "this" (line 19), as getting the "window"  object. When babel runs over the file it renames the variable "this" into "undefined" and then the baguetteBox object will be not defined.

It is working fine when "this" is renamed to "window". I have set babel to ignore the file for now. If you decide to change this, then we can remove the ignore parameter and use the official file as it is without babel problems.

Oh, and thanks for this great script!

**Comment by feimosi** [comment] 2017-03-02 22:22
Hi, do you use some kind of a bundler? baguetteBox.js is written in the [UMD](https://github.com/umdjs/umd) format, so when using modules it's not gonna be assigned to the `window` object. Could share more info how you import the script?

**Comment by godmok** [comment] 2017-03-16 11:03
Hi feimosi, sorry to be so late.
Neither do I use a bundler nor concat it together with other files.

I run over it with babel. I can look into it later again, but like I said, it is working now.
Have to check it with uglifyjs, too.

**Comment by feimosi** [comment] 2017-03-16 14:27
Ok, I know what's wrong. Babel assumes you're writing JS files in module-style, thus there's no global object available.

In your case, if you're not using any module bundler, you should add `modules: false` option to `.babelrc`:
```json
{
  "presets": [
    [ "es2015", { "modules": false } ]
  ]
}
```

See: http://stackoverflow.com/a/34983495

This is not something I can fix in the script. That's an intended behaviour.

**Comment by godmok** [comment] 2017-03-27 17:51
you are right, it looks like a babel problem.
But if I add that option I get an error... I set the file to ignore, so no problem at all.
Oh yeah, and your script is awesome :D

**Closed** 2017-03-27 17:52 UTC

**Comment by feimosi** [comment] 2017-03-27 18:31
Thanks! I'm really glad you like it :D
