### ISSUE TITLE
Infinite carousel

### ISSUE THREAD

**Issue by sqndr** [feimosi/baguetteBox.js#136] opened 2016-12-21 18:09 UTC
Would it be possible to have an infinite carousel? So that when you're on the last slide and you click the next button, you go back to the first slide.

**Comment by feimosi** [comment] 2016-12-21 19:13
Duplicate of #41.
Sorry, but currently it's not possible. I'm planning such a feature for the 2.0 release though.

**Closed by feimosi** 2016-12-21 19:13 UTC

**Comment by kavithakavithap** [comment] 2018-11-27 07:35
Is there any updates on this feature?

**Comment by webmasterpf** [comment] 2022-12-06 16:09
Hello,
I'm interesting in this feature too. any news about ?
Thanks
