### ISSUE TITLE
Support browsers that don't support SVG

### ISSUE THREAD

**Issue by jcubic** [feimosi/baguetteBox.js#126] opened 2016-09-11 14:11 UTC
I have old Android phone with default browser that don't support svg and icons are not visible. It would be nice if baguetteBox check if svg is supported before using it.

**Comment by feimosi** [comment] 2016-09-11 17:38
Hi, I've already got a fallback for SVG support:
https://github.com/feimosi/baguetteBox.js/blob/dev/src/baguetteBox.js#L162

The reason you don't see any buttons is because they are hidden on mobile devices by default. You may want to use `{ buttons: true }` option to enabled them.

**Comment by jcubic** [comment] 2016-09-11 18:21
It work for prev/next but close is not visible.

**Comment by feimosi** [comment] 2016-09-12 06:37
Ok, interesting, but I've got a clue, it may be caused by not closing the entity value here:
https://github.com/feimosi/baguetteBox.js/blob/dev/src/baguetteBox.js#L281
Can you change that line to:
`closeButton.innerHTML = supports.svg ? closeX : '&times;';`
and test it on your device?

**Comment by jcubic** [comment] 2016-09-12 08:04
Yes it work.

**Closed** 2016-09-12 09:33 UTC
