### ISSUE TITLE
Click image > next

### ISSUE THREAD

**Issue by bakman2** [feimosi/baguetteBox.js#23] opened 2015-04-18 16:30 UTC
As subject, is this possible somehow ?

Maybe also nice to make it possible to change the arrow colors via options or css.

**Comment by feimosi** [comment] 2015-04-18 19:10
Hi,
I was thinking about that feature at the beginning, but then it came to 
my mind that I'd need some kind of overlay over the image, what could 
prevent right-click mouse actions like 'save image as', so I gave up 
that idea.

Regarding the arrows, it's impossible with CSS as they're hardcoded as 
SVG in the .js file. Of course you can always change the color by 
modifying that file, but I'll think about a new options' field in a 
future release.

**Comment by bakman2** [comment] 2015-04-18 19:37
I am trying to fix it myself for the click.

I have added:
     bind(overlay, 'click', function(event) {
            // Save x axis position
            showNextImage();
        });

**Comment by bakman2** [comment] 2015-04-18 19:47
fix:
     bind(overlay, 'click', function(event) {
            if(event.target && event.target.nodeName !== 'IMG' && event.target.nodeName !== 'FIGCAPTION'){
                hideOverlay();
            }
            else{
                showNextImage();
            }
        });

**Comment by feimosi** [comment] 2015-04-19 15:49
I see, but this works only for moving forward. It's more common when you have the image divided into two-clickable areas.
Anyway I don't see the need for that in this script, but feel free to use it yourself.
Regards

**Comment by bakman2** [comment] 2015-04-19 16:48
agreed. it works for me.

btw in Safari on OSX 10.10 the gallery behaves quite slow and stutters, would could be the cause of this ?

**Comment by bakman2** [comment] 2015-04-19 16:53
Example: www.richardbakker.com

**Comment by feimosi** [comment] 2015-04-19 17:27
hmm hard to say, unfortunately I don't have access to OSX to test that. If it happens only on Safari, you could check out older / newer versions. The animations are based on CSS transitions, so it may be some rendering engine problem.

**Comment by bakman2** [comment] 2015-04-19 17:34
It happens on chrome as well albeit a little better.

**Comment by feimosi** [comment] 2015-04-19 17:42
That's strange, but there's not much I can do right now.

**Comment by bakman2** [comment] 2015-04-19 18:40
Strange indeed. It appears to be caused by the loading-spinner.
I have commented it out and it works perfectly now:

       // var spinner = document.querySelector('#baguette-img-' + index + ' .spinner');
            // figure.removeChild(spinner);
       // figure.innerHTML = '<div class="spinner">' +
        //     '<div class="double-bounce1"></div>' +
        //     '<div class="double-bounce2"></div>' +
        //     '</div>';

**Comment by feimosi** [comment] 2015-04-24 17:29
Ok, I see, so it looks like the rendering engine can't hold it all. Strange as the spinner is a simple css animation. 
I hope that's a temporary problem, because the only solution as you've noticed is to remove it entirely.

**Comment by bakman2** [comment] 2015-04-24 17:36
I suspect it is not the animation, but creating/removing elements is quite expensive DOM manipulation.

**Comment by feimosi** [comment] 2015-04-24 17:52
Any ideas how to optimize it? Considering that each image has its own loading spinner.

**Comment by feimosi** [comment] 2015-05-23 12:04
Does the stuttering still occur on OSX?

Regarding the colors changing via options, I've been thinking about a possible solution, but unfortunately there isn't any reasonable one as it relies on css and :hover.

**Comment by feimosi** [comment] 2015-07-20 15:54
@bakman2 can I close this issue? Couldn't be reproduced.

**Closed** 2015-08-06 09:38 UTC
