### ISSUE TITLE
Prev/Next buttons not showing in Chrome

### ISSUE THREAD

**Issue by devtrends** [feimosi/baguetteBox.js#118] opened 2016-07-18 02:37 UTC
Chrome Version 51.0.2704.106

Previous and next buttons are not showing on demo site gallery example though close button does display. Seems fine in other browsers.

**Comment by feimosi** [comment] 2016-07-18 18:50
It works for me on:
_Version 51.0.2704.106 m (64-bit)_
_Windows 10_

Could you make a hard refresh of the demo site and try once again? Does it happen for every gallery? Are there any errors on the console?

**Comment by devtrends** [comment] 2016-07-18 18:59
Hmm. Strange. Tried three machines. Two Windows 10 64 bit both fail. ChromeOS one works ok. All using same version of Chrome. No errors in console. All galleries on demo site fail (also failing on my own site). Hard refresh doesn't fix anything.

**Comment by feimosi** [comment] 2016-07-18 19:19
Indeed, that's strange. Could you try in incognito mode without any extensions enabled? 
Also please try to inspect the code yourself, whether it contains the buttons markup. As long as I can't reproduce it I'm helpless.

**Comment by devtrends** [comment] 2016-07-18 19:22
Incognito / no extensions is the same. Markup includes them but they have an inline style of display: none:

`<button type="button" id="next-button" aria-label="Next" class="baguetteBox-button" style="display: none;">`

**Comment by feimosi** [comment] 2016-07-18 19:39
Ah, now I got enlightened. Do your machines have a touchscreen? This may be connected to:
https://github.com/feimosi/baguetteBox.js/issues/95

**Comment by devtrends** [comment] 2016-07-18 19:40
only one of the not-working machines has a touchscreen.

**Comment by feimosi** [comment] 2016-07-18 19:42
Can you try running the script with the following option?
```js
{
  buttons: true
}
```

**Comment by devtrends** [comment] 2016-07-18 20:05
yep. that works and is fine as a workaround for now. thanks.

will leave issue open as a marker to fix underlying issue but feel free to close.

**Comment by feimosi** [comment] 2016-07-18 20:12
Then it's definitely connected to touch events.
When you have some time, please run in the console `window.ontouchstart` for every machine and write me whether they return `undefined` or an object (of what kind).

**Comment by devtrends** [comment] 2016-07-21 14:33
window.ontouchstart returns null for both touch and non-touch win10 machines

**Comment by feimosi** [comment] 2016-07-22 20:07
Is it really null or undefined? Could you now run `'ontouchstart' in window` in the console ?

**Comment by XhmikosR** [comment] 2016-07-23 11:26
I had a similar issue with Firefox, and I ended up clearing the related setting from its config. It was the simulate touch in mobile toolbar. Not sure if Chrome has something similar.

**Comment by XhmikosR** [comment] 2016-07-23 11:27
Oh, also see #95

**Comment by feimosi** [comment] 2016-07-23 11:33
I was thinking about #95 at first, but as @devtrends mentioned:
> only one of the not-working machines has a touchscreen.

so it shouldn't fail on a machine without a touchscreen.

**Comment by XhmikosR** [comment] 2016-07-23 11:35
Yeah, so it looks like something similar to the other issue I hit myself. https://github.com/feimosi/baguetteBox.js/issues/78

**Comment by feimosi** [comment] 2016-08-03 16:20
@devtrends so could you run `'ontouchstart' in window` on each device?

**Comment by devtrends** [comment] 2016-08-03 17:51
`'ontouchstart' in window` returns true on both touch and non-touch devices.

**Comment by XhmikosR** [comment] 2016-08-03 18:07
Seems like the issue I had. Uncheck the option from dev tools to emulate touch events or something similar.

**Comment by devtrends** [comment] 2016-08-03 18:28
https://bugs.chromium.org/p/chromium/issues/detail?id=557565

**Comment by feimosi** [comment] 2016-08-04 13:39
Ok, thanks, I'm gonna close this issue as the problem is out of my reach. Hopefully they'll fix it soon.

**Closed by feimosi** 2016-08-04 13:39 UTC
Labels: bug
